### ISSUE TITLE
Core worlds error on start 

### ISSUE THREAD

**Issue by Peav84** [CreepsterLGC/Core#11]
Windows 7 64bit
Minecraft 1.8
Forge 1521
Sponge Dev 726
Core chat,Portals, Worlds, zones, tickets
World edit-forge-mc1.8-6.1

[21:01:02] [Server thread/ERROR] [Sponge]: [Plugin Class: main.java.me.creepster
lgc.coreworlds.CoreWorlds][Handler: onEnable]
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0
_65]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0
_65]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1
.8.0_65]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_65]
        at org.spongepowered.mod.plugin.SpongeModPluginContainer.handleModStateE
vent(SpongeModPluginContainer.java:127) [SpongeModPluginContainer.class:1.8-1521
-2.1DEV-726+spongeproject-ci-b726.git-bd07085cf983e5024b395e249c647f6465c1295c]
        at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1
.8.0_65]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_65]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscribe
r.java:74) [minecraft_server.1.8.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(Sy
nchronizedEventSubscriber.java:47) [minecraft_server.1.8.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [mine
craft_server.1.8.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.jav
a:304) [minecraft_server.1.8.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) [minecraf
t_server.1.8.jar:?]
        at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(
LoadController.java:212) [LoadController.class:?]
        at net.minecraftforge.fml.common.LoadController.propogateStateMessage(Lo
adController.java:190) [LoadController.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0
_65]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0
_65]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1
.8.0_65]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_65]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscribe
r.java:74) [minecraft_server.1.8.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(Sy
nchronizedEventSubscriber.java:47) [minecraft_server.1.8.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [mine
craft_server.1.8.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.jav
a:304) [minecraft_server.1.8.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) [minecraf
t_server.1.8.jar:?]
        at net.minecraftforge.fml.common.LoadController.distributeStateMessage(L
oadController.java:119) [LoadController.class:?]
        at net.minecraftforge.fml.common.Loader.serverStarting(Loader.java:781)
[Loader.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarting(F
MLCommonHandler.java:319) [FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(Dedicated
Server.java:286) [po.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:438) [M
inecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_65]
Caused by: java.lang.NoSuchMethodError: ninja.leaping.configurate.ConfigurationN
ode.getList(Ljava/util/function/Function;)Ljava/util/List;
        at main.java.me.creepsterlgc.coreworlds.files.FileWorlds.setup(FileWorld
s.java:85) ~[FileWorlds.class:?]
        at main.java.me.creepsterlgc.coreworlds.CoreWorlds.onEnable(CoreWorlds.j
ava:41) ~[CoreWorlds.class:?]
        ... 30 more

**Comment by CreepsterLGC** [comment]
Update to SpongeForge 801+ :-)
