### ISSUE TITLE
NoSuchMethod error in console

### ISSUE THREAD

**Issue by ghost** [CreepsterLGC/Core#8]
<pre>
[22:06:49] [Server thread/ERROR] [Sponge]: Could not pass ChangeBlockEvent$Break$Impl to SpongePlugin:Core Plugin{unknown}
java.lang.NoSuchMethodError: org.spongepowered.api.data.Transaction.getDefaultReplacement()Lorg/spongepowered/api/data/DataSerializable;
        at me.creepsterlgc.core.events.EventPlayerBlockPlace.onPlayerBlockPlace(EventPlayerBlockPlace.java:33) ~[EventPlayerBlockPlace.class:?]
        at org.spongepowered.common.event.listener.BreakListener_EventPlayerBlockPlace_onPlayerBlockPlace13.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:92) ~[RegisteredListener.class:1.8-1530-2.1-DEV-767]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:215) [SpongeModEventManager.class:1.8-1530-2.1-DEV-767]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:178) [SpongeModEventManager.class:1.8-1530-2.1-DEV-767]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:247) [SpongeModEventManager.class:1.8-1530-2.1-DEV-767]
        at net.minecraft.world.World.handlePostTickCaptures(World.java:806) [aqu.class:?]
        at net.minecraft.network.PacketThreadUtil$1.onProcessPacket(SourceFile:60) [ih.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [ih.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_40]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_40]
        at net.minecraftforge.fml.common.FMLCommonHandler.callFuture(FMLCommonHandler.java:714) [FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:656) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:364) [po.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40]
</pre>

**Comment by ghost** [comment]
Btw please close issue when you fix the problem. Not before like my other issues.

**Comment by ghost** [comment]
Looks like this problem is solved...
